### ISSUE TITLE
파일 사이즈 비교 함수 코드 작성

### ISSUE THREAD

**Issue by soojeo** [kwst29/Assignment2#10]
파일 사이즈 비교 함수 코드작성해주세요

**Comment by ldayeon** [comment]
void sizecmp(void)
{
	if((int)stat1.st_size>(int)stat2.st_size)
		printf("text1 is bigger\n");
	else if((int)stat1.st_size<(int)stat2.st_size)
		printf("text2 is bigger\n");
	else
		printf("sizes are equal\n");
}

파일 사이즈 비교함수 코드 작성했습니다. 확인 부탁드립니다.

**Comment by soojeo** [comment]
네 하시면 될 거 같아여
