### ISSUE TITLE
파일 시간 받아오기 -코드작성

### ISSUE THREAD

**Issue by soojeo** [kwst29/Assignment2#11]
파일 시간 받아오기 코드작성해주세요

**Comment by kwst29** [comment]
코드 작성 중에 에러 발견했습니다. 
항상 same으로 뜨는데
해결할 수 있는 방법이 있나요?

**Comment by ldayeon** [comment]
https://blog.naver.com/ultract2/220477718658

이 사이트 참고하고 수정해주세요.
