### ISSUE TITLE
파일 시간 받아오기 - 코드 리뷰

### ISSUE THREAD

**Issue by soojeo** [kwst29/Assignment2#13]
파일 시간 받아오기 코드 리뷰 해주세요

**Comment by kwst29** [comment]
void filetime1(void)
{
        time1=localtime(&stat1.st_mtime);
}
의 형태로 구현하려 합니다.

**Comment by soojeo** [comment]
음... 괜찮은거 같네요

**Comment by kwst29** [comment]
PR 진행하겠습니다.
