### ISSUE TITLE
파일 수정 날짜(월/일) 비교 - 코드 작성

### ISSUE THREAD

**Issue by ldayeon** [kwst29/Assignment2#19]

**Comment by ldayeon** [comment]
void datecmp(void)
{
	if(time1.tm_yday<time2.tm_yday)
		printf("text1 is early.\n");
	else if(time1.tm_yday>time2.tm_yday)
		printf("text2 is early.\n");
	else
		printf("same time\n");
}

위와 같이 날짜 비교함수를 작성해봤는데 문제가 있는지 확인해주시면 감사하겠습니다.

**Comment by kwst29** [comment]
네 PR 부탁드립니다.
