### ISSUE TITLE
파일 수정 시간(시/분) 비교 - 기반 기술 조사

### ISSUE THREAD

**Issue by ldayeon** [kwst29/Assignment2#21]

**Comment by ldayeon** [comment]
파일 수정 시간 비교 함수 코드 작성하는데 참고한 사이트입니다. 링크 첨부합니다.

https://blog.naver.com/cidsang/19159296

**Comment by kwst29** [comment]
자료 바탕으로 코드 작성해주세요
확인후 PR하겠습니다
