### ISSUE TITLE
파일 수정 시간(시/분) 비교 - 코드 작성

### ISSUE THREAD

**Issue by ldayeon** [kwst29/Assignment2#22]

**Comment by ldayeon** [comment]
void timecmp(void)
{
	if(time1.tm_hour<time2.tm_hour)
		printf("text1 is early.\n");
	else if(time1.tm_hour>time2.tm_hour)
		printf("text2 is early.\n");
	else
	{		
		if(time1.tm_min<time2.tm_min)
			printf("text1 is early.\n");
		else if(time1.tm_min>time2.tm_min)
			printf("text2 is early.\n");
		else
		printf("same time\n");
	}		

파일 수정 시간 비교 함수 작성했습니다.

**Comment by kwst29** [comment]
확인했습니다 PR해주세요!
