### ISSUE TITLE
파일 정보 받아오기 - 코드 작성

### ISSUE THREAD

**Issue by kwst29** [kwst29/Assignment2#3]
파일 정보 받아오는 코드를 작성해서 보내주세요

**Comment by soojeo** [comment]
//파일 1의 정보를 가져오는 함수 작성
void filestat1(void)
{
   if(stat("text1",&stat1)==-1)
   {
      printf("text1 is not opened.\n");
   }
}

//파일 2의 정보를 가져오는 함수 작성
void filestat2(void)
{
   if(stat("text2",&stat2)==-1)
   {
      printf("text2 is not opened.\n");
   }
}
이렇게 작성하면 되나요 부장님

**Comment by kwst29** [comment]
네 PR 보내주세요.
