### ISSUE TITLE
블락 사이즈 관련 수정요청

### ISSUE THREAD

**Issue by kwst29** [kwst29/Assignment2#37]
파이 블락 사이즈 비교함수를 재구현 해야할 것 같습니다.

**Comment by soojeo** [comment]
printf("\n block compare \n");
    if((int)stat1.st_blocks>(int)stat2.st_blocks)
            printf("text1 is bigger\n");
    else if((int)stat1.st_blocks<(int)stat2.st_blocks)
            printf("text2 is bigger\n");
    else
            printf("same\n");
해당 코드로 수정하겠습니다

**Comment by kwst29** [comment]
감사합니다.
