### ISSUE TITLE
파일 시간 받아오기 - 기반 기술 조사

### ISSUE THREAD

**Issue by soojeo** [kwst29/Assignment2#7]
파일 시간 받아오기 기반 기술 조사 해주세요

**Comment by kwst29** [comment]
https://blog.naver.com/rjseorl95/221057464334
에서 시간 받아오는 함수에 대한 설명을 볼 수 있습니다

**Comment by kwst29** [comment]
http://downman.tistory.com/191

에서 시간 관련 함수에 대한 정보를 얻을 수 있습니다.
