### ISSUE TITLE
파일 사이즈 비교 함수 기반 기술 조사

### ISSUE THREAD

**Issue by soojeo** [kwst29/Assignment2#8]
파일 사이즈 비교 함수 기반 기술 조사 해주세요

**Comment by ldayeon** [comment]
아래의 링크는 파일 사이즈 비교 함수를 작성하는데 참고한 사이트입니다.

https://bestheroz.blog.me/112134338

**Comment by kwst29** [comment]
참고 바탕으로  코드 작성 부탁드립니다!
