### ISSUE TITLE
파일블락수비교 - 코드작성

### ISSUE THREAD

**Issue by kwst29** [kwst29/Assignment2#9]
코드 작성과 관련된 부분 이슈로 올려주세요

**Comment by soojeo** [comment]
if((int)stat1.st_size>(int)stat2.st_size)
                printf("text1 is bigger");
        else if((int)stat1.st_size<(int)stat2.st_size)
                printf("text2 is bigger");
        else
                printf("same");
이래 해도 괜찮을까요

**Comment by kwst29** [comment]
PR올려주세요
